

#Catalogos a numericos
MUNICIPIOS$CLAVE_MUNICIPIO <- as.numeric(MUNICIPIOS$CLAVE_MUNICIPIO)
MUNICIPIOS$CLAVE_ENTIDAD <- as.numeric(MUNICIPIOS$CLAVE_ENTIDAD)
ENTIDADES$CLAVE_ENTIDAD <- as.numeric(ENTIDADES$CLAVE_ENTIDAD)



COVID19_Mexico$ORIGEN <- ORIGEN$DESCRIPCION[COVID19_Mexico$ORIGEN]
COVID19_Mexico$SECTOR <- SECTOR$DESCRIPCION[COVID19_Mexico$SECTOR]
COVID19_Mexico$ENTIDAD_UM <- ENTIDADES$ENTIDAD_FEDERATIVA[COVID19_Mexico$ENTIDAD_UM]
COVID19_Mexico$SEXO <- SEXO$DESCRIPCION[COVID19_Mexico$SEXO]
COVID19_Mexico$ENTIDAD_NAC <- ENTIDADES$ENTIDAD_FEDERATIVA[COVID19_Mexico$ENTIDAD_NAC]

#cATALOGO SI_NO
COVID19_Mexico$TIPO_PACIENTE <- TIPO_PACIENTE$DESCRIPCION[COVID19_Mexico$TIPO_PACIENTE]
COVID19_Mexico$INTUBADO <- SI_NO$DESCRIPCION[COVID19_Mexico$INTUBADO]
COVID19_Mexico$NEUMONIA <- SI_NO$DESCRIPCION[COVID19_Mexico$NEUMONIA]
COVID19_Mexico$EMBARAZO <- SI_NO$DESCRIPCION[COVID19_Mexico$EMBARAZO]
COVID19_Mexico$HABLA_LENGUA_INDIG <- SI_NO$DESCRIPCION[COVID19_Mexico$HABLA_LENGUA_INDIG] #Cambio el 140420 de INDI a INDIG
COVID19_Mexico$DIABETES <- SI_NO$DESCRIPCION[COVID19_Mexico$DIABETES]
COVID19_Mexico$EPOC <- SI_NO$DESCRIPCION[COVID19_Mexico$EPOC]
COVID19_Mexico$ASMA <- SI_NO$DESCRIPCION[COVID19_Mexico$ASMA]
COVID19_Mexico$INMUSUPR <- SI_NO$DESCRIPCION[COVID19_Mexico$INMUSUPR]
COVID19_Mexico$HIPERTENSION <- SI_NO$DESCRIPCION[COVID19_Mexico$HIPERTENSION]
COVID19_Mexico$OTRA_COM <- SI_NO$DESCRIPCION[COVID19_Mexico$OTRA_COM] #Cambio el 140420 de CON a COM
COVID19_Mexico$CARDIOVASCULAR <- SI_NO$DESCRIPCION[COVID19_Mexico$CARDIOVASCULAR]
COVID19_Mexico$OBESIDAD <- SI_NO$DESCRIPCION[COVID19_Mexico$OBESIDAD]
COVID19_Mexico$RENAL_CRONICA <- SI_NO$DESCRIPCION[COVID19_Mexico$RENAL_CRONICA]
COVID19_Mexico$TABAQUISMO <- SI_NO$DESCRIPCION[COVID19_Mexico$TABAQUISMO]
COVID19_Mexico$OTRO_CASO <- SI_NO$DESCRIPCION[COVID19_Mexico$OTRO_CASO]
COVID19_Mexico$MIGRANTE<- SI_NO$DESCRIPCION[COVID19_Mexico$MIGRANTE]
COVID19_Mexico$UCI <- SI_NO$DESCRIPCION[COVID19_Mexico$UCI]


COVID19_Mexico$NACIONALIDAD <- NACIONALIDAD$DESCRIPCION[COVID19_Mexico$NACIONALIDAD]
COVID19_Mexico$RESULTADO <- RESULTADO$DESCRIPCION[COVID19_Mexico$RESULTADO]



COVID19_Mexico <- COVID19_Mexico %>% left_join(MUNICIPIOS, by = c("ENTIDAD_RES"="CLAVE_ENTIDAD","MUNICIPIO_RES"="CLAVE_MUNICIPIO"))
COVID19_Mexico$ENTIDAD_RES <- ENTIDADES$ENTIDAD_FEDERATIVA[COVID19_Mexico$ENTIDAD_RES]




saveRDS(COVID19_Mexico, here::here("data/COVID19_Mexico.rds"))

